version: '3'
services:
  email_services:
    image: creativitykills/nginx-php-server
    container_name: emails
    ports:
    - "44680:80"
    volumes:
    - ./:/var/www
    networks:
    - backend

  mysql:
    container_name: db_mysql_email
    image: mysql:5.7
    ports:
    - "33070:3306"
    environment:
    - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
    - "MYSQL_DATABASE=${DB_DATABASE}"
    - "MYSQL_USERNAME=${DB_USERNAME}"
    - "MYSQL_PASSWORD=${DB_PASSWORD}"
    volumes:
    - "./db/mysql/initdb.d:/docker-entrypoint-initdb.d"
    networks:
    - backend

  redis:
    container_name: redis_email
    image: redis:4.0
    ports:
    - "6382:6379"
    networks:
    - backend

networks:
  backend:
    driver: bridge
